#!/bin/bash
POSPAR1 = "$1"
POSPAR1 = "$2"
POSPAR1 = "$3"

echo "The first postional parameter is : $POSPAR1 ."
echo "The second postional parameter is : $POSPAR2 ."
echo "The third postional parameter is : $POSPAR3 ."
echo
echo "Total number of postional parameter is : $# ."



